### ISSUE TITLE
Remove ':' from filename in OldResources/DSA%20Practice%20for%201:30:17.md

### ISSUE THREAD

**Issue by agorenst** [joinpursuit/Pursuit-Core-DSA#32]
(I hit "enter" while initially creating this issue, sorry if it sent an unclear automated email.)

The file listed above has a colon (:) in its filename. That is an illegal filename in Windows, and I've found that causes issues when synching with the repository. Also it means people using Windows can't read or edit the file locally :).

**Comment by alejo4373** [comment]
@agorenst I apologize for the delay. This should be fixed with PR #40
